name: tdd_test
description: "A new Flutter project for testing with tdd."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  dio: ^5.7.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  logger: ^2.4.0
  pretty_dio_logger: ^1.4.0
  image: ^4.2.0
  flutter_localization: ^0.2.2
  flutter_secure_storage: ^9.2.2
  dartz: ^0.10.1
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/
    - assets/mocks/
    - assets/pngs/
    - assets/svgs/
